openapi: 3.1.0
info:
  license:
    name: Peridio
    url: https://github.com/peridio/parasola/blob/main/LICENSE
  description: >-
    The Peridio Device API facilitates device-based operations within Peridio v1
    (Cremini).
  title: Peridio Device API
  version: 1.0.0
servers:
  - url: https://device.cremini.peridio.com
security:
  - MutualTLS: []
x-tagGroups:
  - name: Endpoints
    tags:
      - Devices
      - Release Orchestration
paths:
  /device/me:
    get:
      operationId: get-device-me
      summary: get device me
      description: >-
        Returns information about the device identified by the request's
        authentication.
      tags:
        - Devices
      parameters:
        - name: expand
          description: >
            See [expanding
            responses](https://docs.peridio.com/admin-api#section/Expanding-Responses).


            |Field|Description|

            |-|-|

            |`cohort`|Includes the cohort information associated to the device.|
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: object
                    properties:
                      identifier:
                        $ref: '#/components/schemas/device-identifier'
                      quarantined:
                        type: boolean
  /device/update:
    get:
      operationId: get-device-update
      summary: get device update
      description: >
        Returns information regarding whether an update is available or not.


        If an update is available, additional information describing the update
        is returned including a presigned URL to acquire the update.
      tags:
        - Devices
      parameters:
        - in: header
          name: x-peridio-uuid
          schema:
            description: The UUID of the currently active firmware on the device.
            $ref: '#/components/schemas/firmware-uuid'
          required: true
        - name: preflight
          in: query
          required: false
          schema:
            type: boolean
            default: false
            description: >
              **When `false`**


              The request will count towards update attempts. `firmware_url` in
              the response will be set to a presigned URL.


              **When `true`**


              The request will not count towards update attempts. `firmware_url`
              in the response will be `null`.


              For example, one may use `true` to check if an update is available
              when you don't yet intend to consume the update so that a device
              does not rack up a number of incomplete updates and eventually get
              quarantined (pending the failure configuration set on the relevant
              deployment).
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: object
                    properties:
                      update_available:
                        description: |
                          An update may not be available if:

                            1. There is no applicable deployment, i.e., the device is up to date.
                            2. The device or an applicable deployment is quarantined.
                        type: boolean
                      firmware_url:
                        description: A presigned HTTPS URL. Expires in 24 hours.
                        oneOf:
                          - type: 'null'
                          - type: string
                      firmware_meta:
                        oneOf:
                          - type: 'null'
                          - $ref: '#/components/schemas/firmware-metadata'
                      deployment_id:
                        description: Uniquely identifies a deployment.
                        oneOf:
                          - type: 'null'
                          - type: integer
  /update:
    get:
      operationId: get-update
      summary: get device update
      description: >
        Returns information regarding whether an update is available or not.


        By default, **only the `status` field is returned**, but you can use the
        `expand` query parameter to obtain the other fields.


        See [expanding
        responses](https://docs.peridio.com/admin-api#section/Expanding-Responses).


        |Field|Description|

        |-|-|

        |`release`|Includes the release record.|

        |`bundle`|Includes the bundle associated to the release.|

        |`manifest`|Includes the manifest including artifact, versions and the
        presigned url.|

        |`manifest.artifact`|Includes the artifact for the binary.|

        |`manifest.artifact_version`|Includes the artifact version for the
        binary.|


        In addition to expanding records you can expand individual fields,
        quering `manifest.url` will return only the `url` field inside the
        manifest.
      tags:
        - Release Orchestration
      parameters:
        - in: header
          name: peridio-release-prn
          schema:
            description: The PRN of the currently active release on the device.
            $ref: '#/components/schemas/prn'
          required: true
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                properties:
                  status:
                    enum:
                      - update
                      - no_update
                      - device_quarantine
                  release:
                    $ref: '#/components/schemas/release'
                  bundle:
                    $ref: '#/components/schemas/bundle'
                  manifest:
                    type: array
                    items:
                      type: object
                      properties:
                        artifact:
                          $ref: '#/components/schemas/artifact'
                        artifact_version:
                          $ref: '#/components/schemas/artifact-version'
                        binary_prn:
                          $ref: '#/components/schemas/prn'
                        hash:
                          type: string
                        url:
                          type: string
                        signatures:
                          $ref: '#/components/schemas/array-of-signatures'
components:
  securitySchemes:
    MutualTLS:
      type: mutualTLS
      description: >-
        The provided client certificate must be signed by a [CA
        certificate](https://docs.peridio.com/reference/ca-certificates)
        registered with Peridio.
  schemas:
    device-identifier:
      description: Uniquely identifies a device within an organization.
      type: string
    firmware-uuid:
      type: string
      format: uuid
      description: Uniquely identifies a firmware.
    product-architecture:
      type: string
    firmware-author:
      type: string
    platform:
      type: string
    product-name:
      type: string
      description: Uniquely identifies a product within an organization.
    vcs-identifier:
      example: d670460b4b4aece5915caf5c68d12f560a9fe3e4
      type: string
    version:
      description: Reference https://hexdocs.pm/elixir/Version.html#module-versions.
      example: 1.0.0-alpha.3
      type: string
    firmware-metadata:
      type: object
      properties:
        architecture:
          $ref: '#/components/schemas/product-architecture'
        author:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/firmware-author'
        description:
          oneOf:
            - type: 'null'
            - type: string
        fwup_version:
          oneOf:
            - type: 'null'
            - type: string
          description: The version of FWUP bundled within the firmware.
        misc:
          oneOf:
            - type: 'null'
            - type: string
        platform:
          $ref: '#/components/schemas/platform'
        product:
          $ref: '#/components/schemas/product-name'
        uuid:
          $ref: '#/components/schemas/firmware-uuid'
        vcs_identifier:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/vcs-identifier'
        version:
          $ref: '#/components/schemas/version'
    prn:
      description: >
        [Peridio Resource Names](/reference/peridio-resource-names) (PRNs)
        uniquely identify Peridio resources.
      type: string
    release-description:
      default: null
      oneOf:
        - type: string
        - type: 'null'
    release-name:
      type: string
    release-phase-type:
      type: string
      enum:
        - static
        - percent
    release-phase-value:
      description: >
        The phase value availability, value ranges from 0.0 to 1.0 count as
        percentages

        0.0 being 0% and 1.0 being 100%. values above 1 are static values
      type: number
      minimum: 0
      maximum: 100
    release-required:
      type: boolean
      default: true
    release-schedule-availability:
      type: string
      format: date-time
    release-schedule-complete:
      type: boolean
    release:
      type: object
      properties:
        bundle_prn:
          $ref: '#/components/schemas/prn'
        cohort_prn:
          $ref: '#/components/schemas/prn'
        description:
          $ref: '#/components/schemas/release-description'
        name:
          $ref: '#/components/schemas/release-name'
        next_release_prn:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/prn'
        organization_prn:
          $ref: '#/components/schemas/prn'
        phase_type:
          $ref: '#/components/schemas/release-phase-type'
        phase_value:
          $ref: '#/components/schemas/release-phase-value'
        required:
          $ref: '#/components/schemas/release-required'
        schedule_date:
          $ref: '#/components/schemas/release-schedule-availability'
        schedule_complete:
          $ref: '#/components/schemas/release-schedule-complete'
        prn:
          $ref: '#/components/schemas/prn'
        inserted_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    artifact-version-item:
      type: object
      properties:
        prn:
          $ref: '#/components/schemas/prn'
        index:
          type: integer
    array-of-ordered-artifact-versions:
      type: array
      items:
        $ref: '#/components/schemas/artifact-version-item'
    bundle:
      type: object
      properties:
        artifact_versions:
          $ref: '#/components/schemas/array-of-ordered-artifact-versions'
        organization_prn:
          $ref: '#/components/schemas/prn'
        prn:
          $ref: '#/components/schemas/prn'
        inserted_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    artifact-description:
      type: string
      minLength: 1
      maxLength: 256
    artifact-name:
      type: string
      minLength: 1
      maxLength: 128
    artifact:
      type: object
      properties:
        description:
          oneOf:
            - $ref: '#/components/schemas/artifact-description'
            - type: 'null'
        inserted_at:
          type: string
          format: date-time
        name:
          $ref: '#/components/schemas/artifact-name'
        organization_prn:
          $ref: '#/components/schemas/prn'
        prn:
          $ref: '#/components/schemas/prn'
        updated_at:
          type: string
          format: date-time
    artifact-version-description:
      type: string
      minLength: 1
      maxLength: 256
    artifact-version-version:
      type: string
      minLength: 5
      maxLength: 16
    artifact-version:
      type: object
      properties:
        artifact_prn:
          $ref: '#/components/schemas/prn'
        description:
          oneOf:
            - $ref: '#/components/schemas/artifact-version-description'
            - type: 'null'
        inserted_at:
          type: string
          format: date-time
        organization_prn:
          $ref: '#/components/schemas/prn'
        prn:
          $ref: '#/components/schemas/prn'
        version:
          $ref: '#/components/schemas/artifact-version-version'
        updated_at:
          type: string
          format: date-time
    signing-signature:
      type: object
      properties:
        signature:
          type: string
          description: >
            An ed25519 signature  of the SHA256 hash of the binary represented
            as a 64-byte hex

            encoded string.
        signing_key_prn:
          $ref: '#/components/schemas/prn'
    array-of-signatures:
      default: null
      oneOf:
        - type: 'null'
        - type: array
          items:
            $ref: '#/components/schemas/signing-signature'
