// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guides: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      collapsed: false,
      items: [
        'getting-started/index',
        'getting-started/qemu',
        'getting-started/raspberry-pi',
        'getting-started/jetson',
        'getting-started/any-target',
      ],
    },
    {
      type: 'category',
      label: 'References',
      collapsible: false,
      collapsed: false,
      items: ['references/explore', 'contributing'],
    },
    {
      type: 'category',
      label: 'Development',
      collapsible: false,
      collapsed: false,
      items: [
        'provisioning',
        'hardware-in-the-loop',
        'sideloading',
        'package-feeds',
        'feed-search',
        'linux-auto-mounting',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsible: false,
      collapsed: false,
      items: [
        'cross-compilation',
        'custom-kernel',
        // 'device-tree-overlays' belongs here, after custom-kernel, but stays
        // unlisted while that page carries `draft: true`. Drafts are dropped
        // from the production build, and a sidebar item naming a dropped doc
        // fails the build. Add it in the same commit that flips the draft flag.
        //
        // The flag waits on all of:
        //   - publish the SDK image avocadolinux/sdk:2024-edge carrying the
        //     overlay compiler, or `avocado install` cannot resolve it
        //   - publish the 2024/edge feed carrying avocado-dtc-overlay-deliver,
        //     or the build hard-errors on a missing delivery hook
        //   - cut an avocado-cli release and name it in the guide; the released
        //     1.0.0-rc.1 does not carry the overlay work despite a from-source
        //     build reporting the same version string
        //   - add `device_tree_overlays` to schemas/avocado-config.json, which
        //     currently rejects the key the guide documents
        //   - ship the image-build toolchain in the SDK, or keep the guide's
        //     "On a brand-new SDK" block
        //
        // Listed here rather than referenced elsewhere on purpose: this comment
        // is the only in-repo trace of the gates, and a pointer to a table or a
        // pull request body is a pointer that goes stale without anyone noticing.
        'seeding-var',
        'customizing-rootfs-initramfs',
        'lockfiles-and-build-stamps',
      ],
    },
    {
      type: 'category',
      label: 'Avocado CLI',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'avocado-cli',
        },
      ],
    },
    {
      type: 'category',
      label: 'Avocado Control',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'avocadoctl',
        },
      ],
    },
    {
      type: 'category',
      label: 'Meta Avocado',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'meta-avocado',
        },
      ],
    },
    {
      type: 'category',
      label: 'MCP',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'mcp',
        },
      ],
    },
  ],
}

export default sidebars
