// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'overview',
    {
      type: 'category',
      label: 'Hardware',
      items: [
        'hardware/support-matrix',
        {
          type: 'category',
          label: 'Advantech',
          items: [
            {
              type: 'category',
              label: 'ICAM-540',
              items: [
                {
                  type: 'html',
                  value:
                    '<a href="/solutions/advantech/icam-540" target="_blank" rel="noopener noreferrer" class="menu__link" style="display: block;">Solution overview</a>',
                },
                {
                  type: 'autogenerated',
                  dirName: 'hardware/advantech/icam-540',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'NVIDIA',
          items: [
            {
              type: 'category',
              label: 'Jetson Orin Nano',
              items: [
                {
                  type: 'html',
                  value:
                    '<a href="/solutions/nvidia/jetson-orin-nano-developer-kit" target="_blank" rel="noopener noreferrer" class="menu__link" style="display: block;">Solution overview</a>',
                },
                {
                  type: 'autogenerated',
                  dirName: 'hardware/nvidia/jetson-orin-nano-developer-kit',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'NXP',
          items: [
            {
              type: 'category',
              label: 'i.MX 8M Plus',
              items: [
                {
                  type: 'html',
                  value:
                    '<a href="/solutions/nxp/imx8mp" target="_blank" rel="noopener noreferrer" class="menu__link" style="display: block;">Solution overview</a>',
                },
                {
                  type: 'autogenerated',
                  dirName: 'hardware/nxp/imx8mp',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'OnLogic',
          items: [
            {
              type: 'category',
              label: 'FR201',
              items: [
                {
                  type: 'html',
                  value:
                    '<a href="/solutions/onlogic/fr201" target="_blank" rel="noopener noreferrer" class="menu__link" style="display: block;">Solution overview</a>',
                },
                {
                  type: 'autogenerated',
                  dirName: 'hardware/onlogic/fr201',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'QEMU',
          items: [
            {
              type: 'autogenerated',
              dirName: 'hardware/qemu',
            },
          ],
        },
        {
          type: 'category',
          label: 'Raspberry Pi',
          items: [
            {
              type: 'category',
              label: 'Raspberry Pi 4 Model B',
              items: [
                {
                  type: 'html',
                  value:
                    '<a href="/solutions/raspberry-pi/raspberry-pi" target="_blank" rel="noopener noreferrer" class="menu__link" style="display: block;">Solution overview</a>',
                },
                {
                  type: 'autogenerated',
                  dirName: 'hardware/raspberry-pi/raspberry-pi-4-model-b',
                },
              ],
            },
            {
              type: 'category',
              label: 'Raspberry Pi 5',
              items: [
                {
                  type: 'html',
                  value:
                    '<a href="/solutions/raspberry-pi/raspberry-pi" target="_blank" rel="noopener noreferrer" class="menu__link" style="display: block;">Solution overview</a>',
                },
                {
                  type: 'autogenerated',
                  dirName: 'hardware/raspberry-pi/raspberry-pi-5',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Seeed',
          items: [
            {
              type: 'category',
              label: 'reTerminal',
              items: [
                {
                  type: 'html',
                  value:
                    '<a href="/solutions/seeed/reterminal" target="_blank" rel="noopener noreferrer" class="menu__link" style="display: block;">Solution overview</a>',
                },
                {
                  type: 'autogenerated',
                  dirName: 'hardware/seeed/reterminal',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Avocado Linux',
      items: [
        {
          type: 'autogenerated',
          dirName: 'avocado-linux',
        },
      ],
    },
    {
      type: 'category',
      label: 'Peridio Core',
      items: [
        {
          type: 'autogenerated',
          dirName: 'peridio-core',
        },
      ],
    },
    {
      type: 'category',
      label: 'Policies',
      items: [
        {
          type: 'autogenerated',
          dirName: 'policies',
        },
      ],
    },
  ],
}

export default sidebars
