// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guides: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      collapsed: false,
      items: [
        'getting-started/index',
        'getting-started/qemu',
        'getting-started/raspberry-pi',
        'getting-started/jetson',
        'getting-started/any-target',
      ],
    },
    {
      type: 'category',
      label: 'References',
      collapsible: false,
      collapsed: false,
      items: ['references/explore', 'contributing'],
    },
    {
      type: 'category',
      label: 'Development',
      collapsible: false,
      collapsed: false,
      items: [
        'provisioning',
        'hardware-in-the-loop',
        'sideloading',
        'package-feeds',
        'feed-search',
        'linux-auto-mounting',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsible: false,
      collapsed: false,
      items: [
        'cross-compilation',
        'custom-kernel',
        // 'device-tree-overlays' belongs here, after custom-kernel, but stays
        // unlisted while that page carries `draft: true`. Drafts are dropped
        // from the production build, and a sidebar item naming a dropped doc
        // fails the build. Add it in the same commit that flips the draft flag
        // (tracked as item 7 of that page's "Release status" table).
        'seeding-var',
        'customizing-rootfs-initramfs',
        'lockfiles-and-build-stamps',
      ],
    },
    {
      type: 'category',
      label: 'Avocado CLI',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'avocado-cli',
        },
      ],
    },
    {
      type: 'category',
      label: 'Avocado Control',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'avocadoctl',
        },
      ],
    },
    {
      type: 'category',
      label: 'Meta Avocado',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'meta-avocado',
        },
      ],
    },
    {
      type: 'category',
      label: 'MCP',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'mcp',
        },
      ],
    },
  ],
}

export default sidebars
