// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guides: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      collapsed: false,
      items: [
        'getting-started/index',
        'getting-started/qemu',
        'getting-started/raspberry-pi',
        'getting-started/jetson',
        'getting-started/any-target',
      ],
    },
    {
      type: 'category',
      label: 'References',
      collapsible: false,
      collapsed: false,
      items: ['references/explore', 'contributing'],
    },
    {
      type: 'category',
      label: 'Development',
      collapsible: false,
      collapsed: false,
      items: [
        'provisioning',
        'hardware-in-the-loop',
        'sideloading',
        'ota',
        'remote-tunnel',
        'package-feeds',
        'feed-search',
        'linux-auto-mounting',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsible: false,
      collapsed: false,
      items: [
        'security/index',
        'security/encrypted-var',
        'security/verity',
        'security/boot-signing',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsible: false,
      collapsed: false,
      items: [
        'cross-compilation',
        'custom-kernel',
        'device-tree-overlays',
        'seeding-var',
        'customizing-rootfs-initramfs',
        'lockfiles-and-build-stamps',
      ],
    },
    {
      type: 'category',
      label: 'Avocado CLI',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'avocado-cli',
        },
      ],
    },
    {
      type: 'category',
      label: 'Avocado Connect API',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'avocado-connect-api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Avocado Control',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'avocadoctl',
        },
      ],
    },
    {
      type: 'category',
      label: 'Meta Avocado',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'meta-avocado',
        },
      ],
    },
    {
      type: 'category',
      label: 'MCP',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'mcp',
        },
      ],
    },
  ],
}

export default sidebars
