// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  agent: ['agent'],
  cli: [
    'cli',
    {
      type: 'autogenerated',
      dirName: 'cli',
    },
  ],
  reference: [
    'reference/overview',
    // 'reference/agent',
    {
      collapsible: false,
      type: 'category',
      label: 'Account Management',
      items: [
        'reference/organizations',
        'reference/peridio-resource-names',
        'reference/users',
      ],
    },
    {
      collapsible: false,
      type: 'category',
      label: 'Binary Management',
      items: [
        {
          type: 'doc',
          label: 'Artifacts',
          id: 'reference/artifacts',
        },
        {
          type: 'doc',
          label: 'Artifact Versions',
          id: 'reference/artifact-versions',
        },
        {
          type: 'doc',
          label: 'Binaries',
          id: 'reference/binaries',
        },
        {
          type: 'doc',
          label: 'Binary Parts',
          id: 'reference/binary-parts',
        },
        {
          type: 'doc',
          label: 'Binary Signatures',
          id: 'reference/binary-signatures',
        },
        'reference/signing-keys',
        {
          type: 'doc',
          label: 'Firmware',
          id: 'reference/firmware',
          customProps: { legacy: true },
        },
      ],
    },
    {
      collapsible: false,
      type: 'category',
      label: 'Data Management',
      items: [
        'reference/webhooks',
      ],
    },
    {
      collapsible: false,
      type: 'category',
      label: 'Device Management',
      items: [
        'reference/ca-certificates',
        {
          type: 'doc',
          label: 'Cohorts',
          id: 'reference/cohorts',
        },
        'reference/device-certificates',
        'reference/devices',
        'reference/just-in-time-provisioning',
        'reference/products',
        'reference/verification-certificates',
        'reference/verification-codes',
      ],
    },
    {
      collapsible: false,
      type: 'category',
      label: 'Release Mangement',
      items: [
        {
          type: 'doc',
          label: 'Bundles',
          id: 'reference/bundles',
        },
        {
          type: 'doc',
          label: 'Deployments',
          id: 'reference/deployments',
          customProps: { legacy: true },
        },
        {
          type: 'doc',
          label: 'Releases',
          id: 'reference/releases',
        },
      ],
    },
  ],
  guides: [
    {
      collapsible: false,
      type: 'category',
      label: 'Binary Management',
      items: [
        'guides/introduction-to-binary-management',
        'guides/multipart-uploads-with-binary-parts',
        'guides/creating-artifact-versions',
        'guides/creating-artifacts',
        'guides/creating-binaries',
        'guides/creating-binary-parts',
        'guides/creating-binary-signatures',
        'guides/creating-firmware',
        'guides/creating-signing-keys',
      ],
    },
    {
      collapsible: false,
      type: 'category',
      label: 'Device Management',
      items: [
        'guides/creating-ca-certificates',
        'guides/creating-devices',
        'guides/creating-products',
        'guides/creating-x509-certificates-with-openssl',
      ],
    },
    {
      collapsible: false,
      type: 'category',
      label: 'Release Management',
      items: [
        'guides/introduction-to-release-management',
        'guides/creating-bundles',
        'guides/creating-deployments',
        'guides/creating-releases',
      ],
    },
  ],
}

module.exports = sidebars
