name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache-dependency-path: src/package-lock.json
          cache: "npm"

      - name: Install dependencies
        run: npm --prefix src ci
      - name: OpenAPI Lint
        run: npm --prefix src exec --no -- redocly lint --config src/redocly.yaml
      - name: ESLint
        run: npm --prefix src run lint
      - name: Docusaurus Build
        run: npm --prefix src run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
