name: Checks
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
          cache: yarn
          cache-dependency-path: src/yarn.lock
      - name: Install dependencies
        run: yarn --cwd src install --frozen-lockfile
      - name: OpenAPI Lint
        run: yarn --cwd src openapi lint
      - name: ESLint
        run: yarn --cwd src lint
      - name: Docusaurus Build
        run: yarn --cwd src build
