name: Checks
on:
  pull_request:
    branches:
      - main
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache-dependency-path: src/package-lock.json
          cache: "npm"
      - name: Install dependencies
        run: npm --prefix src ci
      - name: OpenAPI Lint
        run: npm --prefix src exec --no -- redocly lint --config src/redocly.yaml
      - name: ESLint
        run: npm --prefix src run lint
      - name: Docusaurus Build
        run: npm --prefix src run build
