name: Test build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: src/yarn.lock

      - name: Install dependencies
        run: yarn --cwd src install --frozen-lockfile
      - name: Test build website
        run: yarn --cwd src build
